version: '3.8'

services:
  postgres-dwh:
    image: postgres:16
    container_name: bi_dwh_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - ./pg_dwh_data:/var/lib/postgresql/data
      - ./data:/data_import
    restart: always

  pgadmin:
    image: dpage/pgadmin4
    container_name: bi_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    ports:
      - "5050:80"
    depends_on:
      - postgres-dwh
    restart: always